### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by mikutown** [Nick-bit233/mai-gen-videob50#10]
**Describe the bug [描述你遇到的错误]**
1. 如果我的b50成绩为小数点后三位而不是四位，系统会默认后三位数字向右对齐，比如No Routine 100.654 在预览界面他会变成100.0654
2. 如果搜索到一些视频名字包含空格的视频，那么文件创建就会失败，比如【maimai DX 外部出力】オモイヨシノ / MASTER AP.mp4的报错：
```
Traceback (most recent call last):
  File "/Users/leafii/Documents/Projects/Python/mai-gen-videob50/utils/video_crawler.py", line 137, in download_video
    order_by('resolution').desc().first().download(output_path)
  File "/Users/leafii/miniconda3/envs/mai-gen-video50/lib/python3.10/site-packages/pytubefix/streams.py", line 364, in download
    with open(file_path, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/leafii/Documents/Projects/Python/mai-gen-videob50/videos/downloads/【maimai DX 外部出力】オモイヨシノ / MASTER AP.mp4'
```

**Envritoment (please complete the following information) [运行环境信息]:**
 - OS 操作系统:macos
 - Python 版本: 3.10

**Comment by wdsj005** [comment]
![image](https://github.com/user-attachments/assets/f9af8e40-bb0e-41c3-ab3c-cf2a592710aa)
![image](https://github.com/user-attachments/assets/42d095d6-bcc2-4229-a05d-16c0e3987fc2)
![image](https://github.com/user-attachments/assets/78bafcd2-3714-49b2-9892-63ba8e7a4843)
在另一帖上说是实装了修改，但还是有这个bug
OS：Win11 23H2 22631.4460

**Comment by Nick-bit233** [comment]
> ![image](https://private-user-images.githubusercontent.com/43010735/392935913-f9af8e40-bb0e-41c3-ab3c-cf2a592710aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NDc4MDAsIm5iZiI6MTczMzQ0NzUwMCwicGF0aCI6Ii80MzAxMDczNS8zOTI5MzU5MTMtZjlhZjhlNDAtYmIwZS00MWMzLWFiM2MtY2YyYTU5MjcxMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAxMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmN2FjZGZlZDE2OWMwNzc5ZWEzODYwNTI3NzgwZDJjNjU1ZTRjMTBjMjAxNTkwN2NkYjYwZGI3ZGJmNWYyMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B98JTTFKtaMpA5-hP5mVgzDQ8kx9nr6z5Mn95GqkFNo) ![image](https://private-user-images.githubusercontent.com/43010735/392935978-42d095d6-bcc2-4229-a05d-16c0e3987fc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NDc4MDAsIm5iZiI6MTczMzQ0NzUwMCwicGF0aCI6Ii80MzAxMDczNS8zOTI5MzU5NzgtNDJkMDk1ZDYtYmNjMi00MjI5LWEwNWQtMTZjMGUzOTg3ZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAxMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZTQ5NDMyYjQ4MjQ5Mzg2MDQxZDdjZWNlNTk3NzAyNDk4ZWJlYzM0ODgyMTE0YmI3ZWEyY2E1ZmI5MDJjMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PrF4Zpbm_Qnp_42WKK8Ev4v0_weZSbChzieWODTvWRA) ![image](https://private-user-images.githubusercontent.com/43010735/392936587-78bafcd2-3714-49b2-9892-63ba8e7a4843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NDc4MDAsIm5iZiI6MTczMzQ0NzUwMCwicGF0aCI6Ii80MzAxMDczNS8zOTI5MzY1ODctNzhiYWZjZDItMzcxNC00OWIyLTk4OTItNjNiYThlN2E0ODQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDAxMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YjBlZjY2NmE4ODBiZDkwODMyY2E5ZDI5M2VlYjIzMGVkODMyMjIwMzg5YjZiM2FhM2M1ODU1YTI1NjlkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wqybiZKt6FKz9lpdql1nVNFysGyblubrriV5cjYKXfI) 在另一帖上说是实装了修改，但还是有这个bug OS：Win11 23H2 22631.4460
> 
> 编辑：图二是图三编辑后重新导入的

源代码已修复，但还没有打更新包，预计今晚发布一下最近的热修复。

**Comment by YHY-create** [comment]
我也出现了这个问题，在下载チエルカ／エソテリカ这首歌的时候出现问题了

正在搜索视频(12/50): チエルカ／エソテリカ DX譜面 Master AP【maimaiでらっくす外部出力】
Error: 搜索视频信息时发生异常: <urlopen error [Errno 2] No such file or directory>

**Comment by YHY-create** [comment]
问题可解决，直接手动搜索YouTube视频并按照成功的歌曲修改json文件即可
