### ISSUE TITLE
Unknown format code 'f' for object of type 'str' 错误

### ISSUE THREAD

**Issue by Hexa5586** [Nick-bit233/mai-gen-videob50#13]
**Describe the bug [描述你遇到的错误]**
在第一次运行pre_gen.py中断后重新启动pre_gen.py进行断点续传，出现以下错误：

#####【Mai-genb50视频生成器 - Step1 信息预处理和素材获取】#####
#####【尝试从水鱼获取乐曲更新数据】 #####
Music data is up-to-date.
##### 【当前配置信息】##### 
  代理: 127.0.0.1:7890
  使用potoken: False
  使用oauth: False
  自动获取potoken: False
#####【1/4】获取用户的b50数据 #####
当前查询的水鱼用户名: HEXA_DOT
#####【2/4】生成b50背景图片 #####
生成B50图片中...
Error: 生成图片时发生异常: Unknown format code 'f' for object of type 'str'
Traceback (most recent call last):
  File "d:\Program Files\mai-gen-videob50\pre_gen.py", line 355, in pre_gen
    generate_b50_images(username, b35_data, b15_data, image_output_path)
  File "d:\Program Files\mai-gen-videob50\gene_images.py", line 44, in generate_b50_images
    acc = f"{record_detail['achievements']:.4f}"
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'

**Comment by Hexa5586** [comment]
我的conda环境为3.11.10，在将record_detail['achievements']换为eval(record_detail['achievements'])后解决了问题

**Comment by Nick-bit233** [comment]
已修复：[829a702](https://github.com/Nick-bit233/mai-gen-videob50/commit/829a702f6b000cedd8977f5937df04141e37cb3c)
