### ISSUE TITLE
生成的test视频没有嵌入谱面预览

### ISSUE THREAD

**Issue by teleaki** [Nick-bit233/mai-gen-videob50#2]
## [1/3]测试网络代理配置...
测试网络代理时发生错误:
Traceback (most recent call last):
  File "C:\Users\000\Desktop\mai-gen-videob50\test.py", line 16, in test_network_proxy
    config = yaml.safe_load(file)
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "D:\Anaconda\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\Anaconda\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\Anaconda\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 38: illegal multibyte sequence

## [2/3]测试图片生成功能...
未找到乐曲11663的难度4的max dx score信息。
## [2/3]图片生成测试成功
下载视频时发生错误: olmYHXHiLGg This request was detected as a bot. Use `use_po_token=True` to view. See more details at https://github.com/JuanBindez/pytubefix/pull/209

## [3/3]测试视频生成功能...
正在合成视频片段: intro_1
正在合成视频片段: NewBest_1
Video Generator Warning:NewBest_1 没有对应的视频, 请检查本地资源
正在合成视频片段: ending_1
MoviePy - Building video videos/test/test_video.mp4.
MoviePy - Writing audio in test_videoTEMP_MPY_wvf_snd.mp3
MoviePy - Done.
MoviePy - Writing video videos/test/test_video.mp4

frame_index:  18%|██████████▏                                               | 90/510 [00:13<00:59,  7.03it/s, now=None]D:\Anaconda\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py:157: UserWarning: In file ./images/BgClips/bg.mp4, 6220800 bytes wanted but 0 bytes read at frame index 89 (out of a total 90 frames), at time 2.97/3.03 sec. Using the last valid frame instead.
  warnings.warn(
frame_index:  18%|██████████▎                                               | 91/510 [00:13<00:57,  7.25it/s, now=None]D:\Anaconda\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py:157: UserWarning: In file ./images/BgClips/bg.mp4, 6220800 bytes wanted but 0 bytes read at frame index 90 (out of a total 90 frames), at time 3.00/3.03 sec. Using the last valid frame instead.
  warnings.warn(
MoviePy - Done !
MoviePy - video ready videos/test/test_video.mp4
## [3/3]视频生成测试成功
#####全部系统功能测试完成！
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x00000243C66402C0>
Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 257, in __del__
    self.close()
  File "D:\Anaconda\Lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 247, in close
    if self.proc.poll() is None:
       ^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\subprocess.py", line 1236, in poll
    return self._internal_poll()
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\subprocess.py", line 1575, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] 句柄无效。

https://github.com/user-attachments/assets/43d86a7b-4b45-49b6-809b-26b77dac052b

**Comment by Nick-bit233** [comment]
第1步中的错误：是由系统文件编码问题导致的，已修复：[e76bb3e](https://github.com/Nick-bit233/mai-gen-videob50/commit/e76bb3ea1c94ee6faeeb6497d3b4606a3ff96fcf)

第2步中的错误：说明你访问youtube的ip地址被ban了，通常是代理服务商提供的ip不是很干净导致的。最简单的方法是更换代理节点或刷新ip后重试。
如果更换各种ip后仍然出现此问题，可能需要手动生成PoToken向服务器证明请求的安全性，请参考：[Add PoToken](https://pytubefix.readthedocs.io/en/latest/user/po_token.html)
稍后会在项目配置中添加Add PoToken的选项，但是这种方法的有效性还有待验证。
关于加入自动PoToken的生成，相对比较困难。如果持续出现此问题，暂时无能为力。

第3步中的错误：通常是由于视频文件在编码后未正常关闭导致的，但这不会影响已生成的最终视频，可以忽略。
