### ISSUE TITLE
运行test.py时报错

### ISSUE THREAD

**Issue by Alvter** [Nick-bit233/mai-gen-videob50#6]
![image](https://github.com/user-attachments/assets/13cb5db3-a230-4e2d-b835-0c2ff7385438)
依赖已安装，未动任何代码

**Comment by Nick-bit233** [comment]
请参考[常见问题](https://github.com/Nick-bit233/mai-gen-videob50/blob/main/README.md#%E8%A7%86%E9%A2%91%E6%8A%93%E5%8F%96%E7%9B%B8%E5%85%B3)
你使用的ip地址可能被youtube限制了，参考[UseTokenGuide][(url](https://github.com/Nick-bit233/mai-gen-videob50/blob/main/UseTokenGuide.md))文档试试添加验证token
