### ISSUE TITLE
【建议】添加其他的查分器

### ISSUE THREAD

**Issue by fon11731** [Nick-bit233/mai-gen-videob50#7]
添加其他的查分器，比如[落雪咖啡屋 maimai DX 查分器](https://maimai.lxns.net/)

**Comment by fon11731** [comment]
能否自行编译，我想自行修改，如果需要的话 项目地址：https://github.com/fon11731/mai-lxns-videob50

**Comment by Nick-bit233** [comment]
欢迎fork和提交pr，如果开发完成后可以添加您到Contributors并将新功能合并到主分支

**Comment by fon11731** [comment]
好的
