### ISSUE TITLE
根据b50生成单曲图片时acc错位

### ISSUE THREAD

**Issue by Alvter** [Nick-bit233/mai-gen-videob50#8]
生成的单曲图片中经常会遇到acc错一位的情况，在我生成的b50中有接近10个是这种情况
![8b8f2a7c93e2202852194ba65bb490d8](https://github.com/user-attachments/assets/459021af-6058-4800-8b12-97c07669e799)

**Comment by Nick-bit233** [comment]
已在 [Commit 6055e47](https://github.com/Nick-bit233/mai-gen-videob50/commit/6055e472c2a6fd51fd0e36ecd28c090ab8eebec1) 中修复。
