### ISSUE TITLE
b50 list index out of range

### ISSUE THREAD

**Issue by YHY-create** [Nick-bit233/mai-gen-videob50#9]
当运行pre_gen.py 生成b50图片时出现以下问题，test生成视频正常。

C:\Users\xxx\PycharmProjects\mai-gen-videob50-main_release_v01\venv\Scripts\python.exe C:\Users\xxx\PycharmProjects\mai-gen-videob50-main_release_v01\pre_gen.py 
#####【Mai-genb50视频生成器 - Step1 信息预处理和素材获取】#####
#####【尝试从水鱼获取乐曲更新数据】 #####
Music data is up-to-date.
##### 【当前配置信息】##### 
  代理: 127.0.0.1:7890
  使用potoken: False
  使用oauth: False
  自动获取potoken: False
#####【1/4】获取用户的b50数据 #####
当前查询的水鱼用户名: xxx
#####【2/4】生成b50背景图片 #####
生成B50图片中...
Error: 生成图片时发生异常: list index out of range

**Comment by Nick-bit233** [comment]
方便提供你查询的时候使用的水鱼用户名吗，好定位一下问题。

**Comment by YHY-create** [comment]
问题已解决，在看了生成的json后发现水鱼查分器的数值格式有问题，手动将"C:\Users\xxx\PycharmProjects\mai-gen-videob50-main_release_v01\b50_datas\b50_config_kuma-ω-.json"中的数值改正为四位小数后就可以成功运行了

**Comment by Nick-bit233** [comment]
已经修复：[972a06c](https://github.com/Nick-bit233/mai-gen-videob50/commit/972a06c531c66ba05b4d3a5830f02c9684ccff5c)
现在对于查询到小数位不足4位的达成率，会自动补全到4位。
可以在水鱼个人设置中取消勾选”对非网页查询的成绩使用掩码“，来获取精确的数据。

> 问题已解决，在看了生成的json后发现水鱼查分器的数值格式有问题，手动将"C:\Users\xxx\PycharmProjects\mai-gen-videob50-main_release_v01\b50_datas\b50_config_kuma-ω-.json"中的数值改正为四位小数后就可以成功运行了
